/*
Guodong Rong

FP_DrawSites.cg
The fragment program for initialization

Copyright (c) 2005-2006 
School of Computing
National University of Singapore
All Rights Reserved.
*/

void main(float4 position   : WPOS,
		  float4 color      : COLOR,
		  float  id			: TEXCOORD0,
		  float2 pos2D		: TEXCOORD1,

  		  out float4 oColor0 : COLOR0,
		  out float4 oColor1 : COLOR1)
{
	oColor0.rg = pos2D;
	oColor0.b = id;
	oColor1 = color;
} // main
